#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail -o monitor
# ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
# ssh-agent productization for macOS
# (c) 2024 Farcloser <apostasie@farcloser.world>
# Distributed under the terms of the MIT license
# ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★

readonly COLOR_RED=1
readonly COLOR_GREEN=2
readonly COLOR_YELLOW=3

logger::stamp(){
  local color="$1"
  local level="$2"
  local i
  shift
  shift

  [ ! "$TERM" ] || [ ! -t 2 ] || >&2 tput setaf "$color" 2>/dev/null || true
  for i in "$@"; do
    >&2 printf "[%s] [%s] %s\n" "$(date 2>/dev/null || true)" "$level" "$i"
  done
  [ ! "$TERM" ] || [ ! -t 2 ] || >&2 tput op 2>/dev/null || true
}

logger::info(){
  logger::stamp "$COLOR_GREEN" "INFO" "$@"
}

logger::warning(){
  logger::stamp "$COLOR_YELLOW" "WARNING" "$@"
}

logger::error(){
  logger::stamp "$COLOR_RED" "ERROR" "$@"
}

fs::ensuredir(){
  local pth="$1"
  mkdir -p "$pth" 2>/dev/null
  [ -d "$pth" ] || {
    logger::error "Failed to create $pth. Check your permissions."
    return 1
  }
}

readonly socket=.ssh/agent

fs::ensuredir "$(dirname "$HOME/$socket")"

# Traces of brew
ssh_agent_binary="${1:-$(brew --prefix 2>/dev/null || printf "/usr")/bin/ssh-agent}"
readonly ssh_agent_binary

# ! ps x | grep ssh-agent | grep "$socket" || {
! pgrep -lf "$ssh_agent_binary" "$HOME/$socket" >/dev/null || {
  logger::error "Agent already running"
  exit 1
}

[ -e "$ssh_agent_binary" ] || {
  logger::error "$ssh_agent_binary is missing"
  exit 1
}

# Delete any spurious remnant
rm -f "$HOME/$socket"

cat <<-EOF > "$HOME/.posh_ssh"
#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail -o monitor
# ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★
# ★ Kingpin             ★
# ★ (c) 2023, Farcloser ★
# ★ MIT License         ★
# ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★ ★

export SSH_AUTH_SOCK="\$HOME/$socket"
EOF

logger::info "Initialization done. Starting the agent now."
# Start it in the foreground
exec "$ssh_agent_binary" -D -a "$HOME/$socket"
